#!/usr/bin/env python3
"""Export TinyNameTransformer weights to a C header for on-device inference."""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import torch

# Repo layout: run from repo root or transformer/
ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / "transformer" / "artifacts"
OUT = ROOT / "include" / "model_weights_generated.h"


def write_float_array(f, name: str, arr: np.ndarray) -> None:
    flat = np.ascontiguousarray(arr, dtype=np.float32).reshape(-1)
    f.write(f"static const float {name}[{flat.size}] = {{\n")
    line: list[str] = []
    for i, x in enumerate(flat):
        line.append(f"{float(x):.8e}f")
        if len(line) >= 10 or i == flat.size - 1:
            f.write("  " + ", ".join(line) + ",\n")
            line.clear()
    f.write("};\n\n")


def main() -> None:
    vocab_path = ART / "vocab.json"
    model_path = ART / "model.pt"
    if not vocab_path.exists() or not model_path.exists():
        raise SystemExit(f"Missing {vocab_path} or {model_path}. Train first.")

    vocab = json.loads(vocab_path.read_text(encoding="utf-8"))
    V = len(vocab)
    state = torch.load(model_path, map_location="cpu")

    pe = state["pos_enc.pe"].numpy()  # (1, T, D)
    assert pe.shape[0] == 1
    T, D = pe.shape[1], pe.shape[2]
    tok = state["token_embed.weight"].numpy()  # (V, D)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by transformer/export_esp32_weights.py — do not edit.\n")
        f.write("#pragma once\n\n")
        f.write("#include <stddef.h>\n\n")
        f.write("namespace mw {\n\n")
        f.write(f"static const int kVocabSize = {V};\n")
        f.write(f"static const int kDModel = {D};\n")
        f.write("static const int kNumHeads = 4;\n")
        f.write(f"static const int kSeqLen = {T};\n")
        f.write("static const int kFf = 256;\n")
        f.write("static const int kNumLayers = 2;\n")
        f.write("static const int kPadId = 0;\n")
        f.write("static const int kBosId = 1;\n")
        f.write("static const int kEosId = 2;\n")
        f.write("static const int kSpaceId = 3;\n")
        f.write("static const float kLnEps = 1e-5f;\n")
        f.write("static const float kAttnMask = -1e9f;\n\n")

        # Vocab chars for itos (index -> char)
        esc = {"\\": "\\\\", '"': '\\"', "\n": "\\n"}
        chars = "".join(vocab)
        f.write("static const char kVocabChars[] = \"")
        for ch in chars:
            f.write(esc.get(ch, ch))
        f.write("\";\n\n")

        write_float_array(f, "kTokEmb", tok)
        write_float_array(f, "kPosEnc", pe[0])

        for layer in range(2):
            pfx = f"layer{layer}"
            write_float_array(f, f"k{pfx}_norm1_w", state[f"encoder.layers.{layer}.norm1.weight"].numpy())
            write_float_array(f, f"k{pfx}_norm1_b", state[f"encoder.layers.{layer}.norm1.bias"].numpy())
            write_float_array(f, f"k{pfx}_in_proj_w", state[f"encoder.layers.{layer}.self_attn.in_proj_weight"].numpy())
            write_float_array(f, f"k{pfx}_in_proj_b", state[f"encoder.layers.{layer}.self_attn.in_proj_bias"].numpy())
            write_float_array(f, f"k{pfx}_out_proj_w", state[f"encoder.layers.{layer}.self_attn.out_proj.weight"].numpy())
            write_float_array(f, f"k{pfx}_out_proj_b", state[f"encoder.layers.{layer}.self_attn.out_proj.bias"].numpy())
            write_float_array(f, f"k{pfx}_norm2_w", state[f"encoder.layers.{layer}.norm2.weight"].numpy())
            write_float_array(f, f"k{pfx}_norm2_b", state[f"encoder.layers.{layer}.norm2.bias"].numpy())
            write_float_array(f, f"k{pfx}_linear1_w", state[f"encoder.layers.{layer}.linear1.weight"].numpy())
            write_float_array(f, f"k{pfx}_linear1_b", state[f"encoder.layers.{layer}.linear1.bias"].numpy())
            write_float_array(f, f"k{pfx}_linear2_w", state[f"encoder.layers.{layer}.linear2.weight"].numpy())
            write_float_array(f, f"k{pfx}_linear2_b", state[f"encoder.layers.{layer}.linear2.bias"].numpy())

        write_float_array(f, "kFinalNorm_w", state["norm.weight"].numpy())
        write_float_array(f, "kFinalNorm_b", state["norm.bias"].numpy())
        write_float_array(f, "kHead_w", state["head.weight"].numpy())
        write_float_array(f, "kHead_b", state["head.bias"].numpy())

        f.write("} // namespace mw\n")

    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
